config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Read all tasks
  get 'tasks', to: 'tasks#index'

  # Create a restaurant
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # Read one task details
  get 'tasks/:id', to: 'tasks#show', as: :task

  # Update/Edit a restaurant
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  # Delete a restaurant
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Personal Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
   <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= render 'form', task: @task %>


<%= link_to tasks_path do %>
  <i class="fa fa-history"></i> Return to the list
<% end %>





<%# <p><%= link_to 'Return to the list', tasks_path %></p>

app/views/tasks/index.html.erb
<h1>Get Things Done! :) </h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        <i class="fa fa-check-square-o"></i>
      <% else %>
        <i class="fa fa-square-o"></i>
      <% end %>
      <%= link_to task.title, task_path(task) %>
    </li>
  <% end %>
</ul>



<%= link_to tasks_new_path do %>
  <i class="fa fa-plus"></i> Add a new task
<% end %>



<%# <%= link_to '+ Create', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'form', task: @task %>

<%= link_to tasks_path do %>
  <i class="fa fa-history"></i> Return to the list
<% end %>

app/views/tasks/show.html.erb
<h1>Description:</h1>

<p><strong>To Do:</strong> <%= @task.title %></p>
<p><strong>Description:</strong> <%= @task.details %></p>




<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Delete', task_path(@task), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %> |
<%= link_to 'Return to the list', tasks_path %>